stages:
  - build
  - release
  - publish

variables:
  RYE_INSTALL_OPTION: "--yes"
  RYE_VERSION: "0.43.0"
  GIT_STRATEGY: clone

build_and_publish:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y curl
    - curl -sSf https://rye.astral.sh/get | bash
    - export PATH="$HOME/.rye/shims:$PATH"
  script:
    - rye sync
    - source .venv/bin/activate
    - rye build --clean
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

upload_wheel:
  stage: release
  only:
    - tags
  script:
    # Example placeholder for GitLab release asset upload
    # Use `curl` or GitLab's release API to upload `dist/*.whl`
    - apt update && apt install -y curl jq
    - export GITLAB_HOST=$CI_SERVER_HOST
    - export GITLAB_TOKEN=$CI_JOB_TOKEN
    - export PROJECT_ID=$CI_PROJECT_ID
    - export TAG_NAME=$CI_COMMIT_TAG
    - |
      for file in dist/*.*; do
        curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --form "file=@$file" \
          "https://${GITLAB_HOST}/api/v4/projects/${PROJECT_ID}/uploads" | jq -r '.markdown' > uploaded_file.md
      done
    - |
      ASSET_LINK=$(cat uploaded_file.md)
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --header "Content-Type: application/json" \
        --data "{
          \"name\": \"$TAG_NAME\",
          \"tag_name\": \"$TAG_NAME\",
          \"description\": \"$ASSET_LINK\"
        }" \
        "https://{GITLAB_HOST}/api/v4/projects/${PROJECT_ID}/releases"